test_that("combine writes correct output", {
	lcp_file <- system.file("extdata/storm_lake.lcp", package="gdalraster")
	rasterfiles <- c(lcp_file, lcp_file)
	bands <- c(4, 5)
	var.names <- c("fbfm", "tree_cov")
	cmb_file <- paste0(tempdir(), "/", "fbfm_cov_cmbid.tif")
	on.exit(unlink(cmb_file))
	df <- combine(rasterfiles, var.names, bands, cmb_file)
	ds <- new(GDALRaster, cmb_file, TRUE)
	dm <- ds$dim()
	chk <- ds$getChecksum(1, 0, 0, dm[1], dm[2])
	ds$close()
	expect_equal(chk, 43024)
})
