test_that("RunningStats works", {
	set.seed(42)
	rs <- new(RunningStats, na_rm=TRUE)
	chunk <- runif(1000)
	rs$update(chunk)
	expect_equal(rs$get_count(), length(chunk))
	expect_equal(rs$get_mean(), mean(chunk))
	expect_equal(rs$get_min(), min(chunk))
	expect_equal(rs$get_max(), max(chunk))
	expect_equal(rs$get_var(), var(chunk))
	expect_equal(rs$get_sd(), sd(chunk))
	chunk2 <- runif(1000)
	rs$update(chunk2)
	expect_equal(rs$get_count(), 2000)
	expect_equal(rs$get_mean(), mean(c(chunk,chunk2)))
	rs$reset()
	expect_equal(rs$get_count(), 0)
	expect_equal(rs$get_sum(), 0)
})
